name: Check QA Jobs

on:
  schedule:
    # Run every day at 15:00 UTC (18:00 Ukrainian time during summer)
    - cron: "0 15 * * *"
  workflow_dispatch:
    # Allow manual triggering

jobs:
  check-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run job checker
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: npm start
