name: Check QA Jobs

on:
  schedule:
    # Run every weekday (Monday to Friday) at 16:00 UTC (19:00 Ukrainian time during summer)
    - cron: "0 16 * * 1-5"
  workflow_dispatch:
    # Allow manual triggering

jobs:
  check-jobs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run job checker
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: npm start

      - name: Commit updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add src/config/last_job.txt
          git commit -m "🔄 last_job value updated: $(cat src/config/last_job.txt)" || echo "No new changes"
          git push
